# Generated by Django 5.1.3 on 2024-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_adminuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='danceschool',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
