# Generated by Django 5.1.3 on 2024-12-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_masterclass_master_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='choreographer',
            name='choreographer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='danceschool',
            name='dance_school_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='danceschool',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='master_class_name',
            field=models.CharField(max_length=50),
        ),
    ]
