# Generated by Django 5.1.3 on 2024-11-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choreographer',
            fields=[
                ('choreographer_id', models.AutoField(primary_key=True, serialize=False)),
                ('choreographer_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=14)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DanceSchool',
            fields=[
                ('dance_school_id', models.AutoField(primary_key=True, serialize=False)),
                ('dance_school_name', models.CharField(max_length=20)),
                ('dance_school_address', models.TextField()),
                ('phone_number', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_id', models.AutoField(primary_key=True, serialize=False)),
                ('style_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('dance_school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.danceschool')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('dance_school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.danceschool')),
            ],
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('master_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('choreographer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.choreographer')),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hall')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='appointments',
            field=models.ManyToManyField(through='app.Appointment', to='app.masterclass'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='master_class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterclass'),
        ),
        migrations.AddField(
            model_name='choreographer',
            name='style_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.style'),
        ),
    ]
